{% set name = "pytorch-forecasting" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytorch_forecasting/pytorch_forecasting-{{ version }}.tar.gz
  sha256: 069af34c17eea2edf5c11c79931097427b88cef8a862457818a03464260e5534

build:
  number: 0
  skip: True  # [py<38 or py>310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - poetry-core 1.5.1
    - poetry-dynamic-versioning 0.23.0
  run:
    - matplotlib-base
    - optuna >=2.3.0
    - pandas >=1.3.0
    - python
    - pytorch >=1.7
    - pytorch-lightning >=1.2.4
    - scikit-learn >=0.24.0,<1.2
    - scipy >=1.8
    - statsmodels

test:
  imports:
    - pytorch_forecasting
  requires:
    - pip
  commands: 
    - pip check

about:
  home: https://github.com/jdb78/pytorch-forecasting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Timeseries forecasting with PyTorch
  description: |
    PyTorch Forecasting is a timeseries forecasting package for PyTorch build on PyTorch Lightning.
    It provides timeseries datasets and dataloaders, various ways to normalize variables
    and a number of neural networks for forecasting. The package is tightly integrated with tensorboard
    for logging.
  doc_url: https://pytorch-forecasting.readthedocs.io/
  dev_url: https://github.com/jdb78/pytorch-forecasting

extra:
  recipe-maintainers:
    - jdb78
  skip-lints:
    - missing_wheel
